LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := X5
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM = "st7701_fwgaplus_dsi_vdo_helitai_vp531"
MTK_SECURITY_SW_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
CUSTOM_LK_USB_UNIQUE_SERIAL = yes
BOOT_LOGO := hd720
DEFINES += SERIAL_NUM_FROM_BARCODE=1
#DEFINES += WITH_DEBUG_DCC=1
#DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += MACH_FPGA_NO_DISPLAY
TRUSTONIC_TEE_SUPPORT=no
MTK_GOOGLE_TRUSTY_SUPPORT=no
MTK_DM_VERITY_OFF = no
MTK_MRDUMP_ENABLE := no
MTK_USERIMAGES_USE_F2FS = yes
SYSTEM_AS_ROOT = yes
