ifndef DRVGEN_OUT
DRVGEN_OUT := $(BUILDDIR)
endif

DRVGEN_OUT_PATH := $(DRVGEN_OUT)/inc

ALL_DRVGEN_FILE :=

ifeq ($(filter mt2601,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_kpd.h
  ALL_DRVGEN_FILE += inc/cust_eint.h
  ALL_DRVGEN_FILE += inc/cust_gpio_boot.h
  ALL_DRVGEN_FILE += inc/cust_gpio_usage.h
  ALL_DRVGEN_FILE += inc/cust_adc.h
  ALL_DRVGEN_FILE += inc/pmic_drv.h
  ALL_DRVGEN_FILE += inc/pmic_drv.c
endif

ifeq ($(filter mt2601 mt8127 mt8163,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_eint_md1.h
endif

ifeq ($(filter mt2601 mt6572 mt6582 mt6592 mt8127,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_eint.dtsi
endif

ifeq ($(filter mt2601 mt6580,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_power.h
endif

ifeq ($(filter mt2601 mt6572 mt6582 mt6592 mt8127 mt8163,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_clk_buf.h
endif

ifeq ($(filter mt2601 mt6572 mt6582 mt6592 mt8127 mt8163,$(PLATFORM)),)
  ALL_DRVGEN_FILE += inc/cust_i2c.h
endif

ifeq ($(PLATFORM),mt2601)
  ALL_DRVGEN_FILE += inc/cust_kpd.h
  ALL_DRVGEN_FILE += inc/cust_eint.h
  ALL_DRVGEN_FILE += inc/cust_gpio_usage.h
  ALL_DRVGEN_FILE += include/target/cust_gpio_boot.h
  ALL_DRVGEN_FILE += include/target/cust_power.h
endif

ifeq ($(PLATFORM),mt6752)
  ALL_DRVGEN_FILE += inc/cust_eint_md2.h
endif

ifeq ($(PLATFORM),mt6595)
  ALL_DRVGEN_FILE += inc/cust_gpio_suspend.h
endif

ifeq ($(PLATFORM),mt6580)
  ALL_DRVGEN_FILE += inc/cust_i2c.dtsi
endif

ifeq ($(PLATFORM),mt8127)
  ALL_DRVGEN_FILE += inc/cust_eint_ext.h
endif

ifeq ($(MTK_PLATFORM),mt6735)
  ALL_DRVGEN_FILE += inc/cust_adc.dtsi
  ALL_DRVGEN_FILE += inc/cust_i2c.dtsi
  ALL_DRVGEN_FILE += inc/cust_md1_eint.dtsi
  ALL_DRVGEN_FILE += inc/cust_kpd.dtsi
  ALL_DRVGEN_FILE += inc/cust_clk_buf.dtsi
  ALL_DRVGEN_FILE += inc/cust_gpio.dtsi
  ALL_DRVGEN_FILE += inc/cust_adc.dtsi
  ALL_DRVGEN_FILE += inc/cust_pmic.dtsi
  ALL_DRVGEN_FILE += inc/mt6735-pinfunc.h
  ALL_DRVGEN_FILE += inc/pinctrl-mtk-mt6735.h
endif

DRVGEN_FILE_LIST := $(addprefix $(DRVGEN_OUT)/,$(ALL_DRVGEN_FILE))
DRVGEN_TOOL := $(PWD)/scripts/dct/DrvGen
DWS_FILE := $(PWD)/target/$(TARGET)/dct/$(if $(CUSTOM_KERNEL_DCT),$(CUSTOM_KERNEL_DCT),dct)/codegen.dws
DRVGEN_PREBUILT_PATH := $(PWD)/target/$(TARGET)
DRVGEN_PREBUILT_CHECK := $(filter-out $(wildcard $(addprefix $(DRVGEN_PREBUILT_PATH)/,$(ALL_DRVGEN_FILE))),$(addprefix $(DRVGEN_PREBUILT_PATH)/,$(ALL_DRVGEN_FILE)))

# Check if DWS file exists, create dummy if not (for CI builds)
DWS_EXISTS := $(shell test -f $(DWS_FILE) && echo 1 || echo 0)
ifeq ($(DWS_EXISTS),0)
  $(warning WARNING: DWS file $(DWS_FILE) not found! Creating dummy file for CI build.)
  $(shell mkdir -p $(dir $(DWS_FILE)))
  $(shell echo "# Dummy DWS file for $(TARGET) - Generated by drvgen.mk" > $(DWS_FILE))
  $(shell echo "[General]" >> $(DWS_FILE))
  $(shell echo "Platform = $(TARGET)" >> $(DWS_FILE))
  $(shell echo "[GPIO]" >> $(DWS_FILE))
  $(shell echo "[EINT]" >> $(DWS_FILE))
  $(shell echo "[ADC]" >> $(DWS_FILE))
  $(shell echo "[KPD]" >> $(DWS_FILE))
endif

.PHONY: drvgen
drvgen: $(DRVGEN_FILE_LIST)

ifneq ($(DRVGEN_PREBUILT_CHECK),)

# Common DrvGen rule with debug and error handling
define DRVGEN_RULE
$(DRVGEN_OUT)/inc/$(1): $(DRVGEN_TOOL) $(DWS_FILE)
	@mkdir -p $$(dir $$@)
	@echo "========================================="
	@echo "Generating $(1) using DrvGen"
	@echo "DWS_FILE: $(DWS_FILE)"
	@echo "Output: $(DRVGEN_OUT_PATH)"
	@echo "========================================="
	@if [ ! -f "$(DWS_FILE)" ]; then \
		echo "ERROR: DWS file not found at $(DWS_FILE)"; \
		echo "Searching for DWS files in target directory:"; \
		find target -name "*.dws" 2>/dev/null || echo "No .dws files found"; \
		exit 1; \
	fi
	@chmod +x $(DRVGEN_TOOL)
	@$(DRVGEN_TOOL) $(DWS_FILE) $(DRVGEN_OUT_PATH) $(DRVGEN_OUT_PATH) $(2)
	@echo "✅ Successfully generated $(1)"
endef

# Generate all required files
$(eval $(call DRVGEN_RULE,cust_kpd.h,kpd_h))
$(eval $(call DRVGEN_RULE,cust_eint.h,eint_h))
$(eval $(call DRVGEN_RULE,cust_gpio_boot.h,gpio_boot_h))
$(eval $(call DRVGEN_RULE,cust_gpio_usage.h,gpio_usage_h))
$(eval $(call DRVGEN_RULE,cust_adc.h,adc_h))
$(eval $(call DRVGEN_RULE,cust_eint_md1.h,md1_eint_h))
$(eval $(call DRVGEN_RULE,cust_power.h,power_h))
$(eval $(call DRVGEN_RULE,pmic_drv.h,pmic_h))
$(eval $(call DRVGEN_RULE,cust_i2c.h,i2c_h))
$(eval $(call DRVGEN_RULE,cust_clk_buf.h,clk_buf_h))
$(eval $(call DRVGEN_RULE,cust_eint_md2.h,md2_eint_h))
$(eval $(call DRVGEN_RULE,cust_gpio_suspend.h,suspend_h))
$(eval $(call DRVGEN_RULE,cust_eint_ext.h,eint_ext_h))
$(eval $(call DRVGEN_RULE,cust_eint.dtsi,eint_dtsi))
$(eval $(call DRVGEN_RULE,pmic_drv.c,pmic_c))
$(eval $(call DRVGEN_RULE,cust_i2c.dtsi,i2c_dtsi))
$(eval $(call DRVGEN_RULE,cust_adc.dtsi,adc_dtsi))
$(eval $(call DRVGEN_RULE,cust_md1_eint.dtsi,md1_eint_dtsi))
$(eval $(call DRVGEN_RULE,cust_kpd.dtsi,kpd_dtsi))
$(eval $(call DRVGEN_RULE,cust_clk_buf.dtsi,clk_buf_dtsi))
$(eval $(call DRVGEN_RULE,cust_gpio.dtsi,gpio_dtsi))
$(eval $(call DRVGEN_RULE,cust_pmic.dtsi,pmic_dtsi))
$(eval $(call DRVGEN_RULE,mt6735-pinfunc.h,mt6735_pinfunc_h))
$(eval $(call DRVGEN_RULE,pinctrl-mtk-mt6735.h,pinctrl_mtk_mt6735_h))

else
# If prebuilt files exist, just copy them
$(DRVGEN_FILE_LIST): $(DRVGEN_OUT)/% : $(DRVGEN_PREBUILT_PATH)/%
	@mkdir -p $(dir $@)
	@echo "Copying prebuilt file: $< -> $@"
	cp -f $< $@
endif
